before_script:
  - cd server
language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - cd ..
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_KEY
  app: vibhaag



