before_script:
- cd server
- npm install
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_KEY
  app: vibhaag



